model:
  output_dim: 11 # Numbers of parameters Theta
  ratios_CNN: 
  - 4 
  - 4 
  - 4 
  - 4
  channel_size: 
  - 16
  - 32
  - 64
  - 128
  size_MLP: 
  - 512
  - 256
  - 128 
  - 64
  - 32
  model_name: "CNN_MLP" # Mettre avec des _ partout

dataset:
  batch_size: 5
  valid_ratio: 0.25
  num_thread: 0
  dataset_type: "list"
  fs: 40000
  resample: True
  resample_rate: 32768

train:
  lr : 0.0001
  epochs: 100001
  save_ckpt: 30
  add_fig: 5
  loss: "MSE"   # "MSE_L1"/"MSE"/"L1"