dataset:
  batch_size: 5
  dataset_type: list
  fs: 40000
  num_thread: 0
  resample: true
  resample_rate: 32768
  valid_ratio: 0.25
model:
  channel_size:
  - 16
  - 32
  - 64
  - 128
  model_name: CNN_MLP
  output_dim: 11
  ratios_CNN:
  - 4
  - 4
  - 4
  - 4
  size_MLP:
  - 512
  - 256
  - 128
  - 64
  - 32
train:
  add_fig: 5
  epochs: 100001
  loss: MSE
  lr: 0.0001
  save_ckpt: 30
