model:
  feature_used: 
  - "spectral_bandwidth"
  - "spectral_centroid"
  - "spectral_rolloff"
  - "rms"
  - "spectral_flatness"
  - "zero_crossing_rate"
  n_features: 2 # or 2
  kernel_svm: 'rbf' #rbf,linear,poly
  C_svm: 
  - 0.1
  - 20
  step: 100
  model_name: "Normalisation_Paires_2" # Mettre avec des _ partout
  plot_title: "Classification de 4 plaques"

dataset:
  dataset_type: "list"
  fs: 40000
  resample: False
  resample_rate: 32768
  valid_ratio: 0.1

train:
  increment: 10