dataset:
  dataset_type: list
  fs: 40000
  resample: false
  resample_rate: 32768
  valid_ratio: 0.1
model:
  C_svm: 0.9
  feature_used:
  - spectral_bandwidth
  - spectral_centroid
  gamma_svm: 0.1
  kernel_svm: rbf
  model_name: SVM_rbf
  plot_title: Test
train:
  increment: 10
